<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7yg0jp8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7yg0jp8/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7yg0jp8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7yg0jp8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7yg0jp8\appProdProjectContainer(array(
    'container.build_hash' => '7yg0jp8',
    'container.build_id' => '55a84f06',
    'container.build_time' => 1533222612,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7yg0jp8');
